# =============================================================================
# service-mgt — creds DB.
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: service-mgt-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.global.secrets.postgresPassword | quote }}
