# =============================================================================
# service-mgt — creds DB.
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: service-mgt-secret
  namespace: stock
type: Opaque
stringData:
  POSTGRES_PASSWORD: "123"
