# =============================================================================
# pgadmin — mật khẩu đăng nhập.
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: stock
type: Opaque
stringData:
  PGADMIN_DEFAULT_PASSWORD: admin
