apiVersion: v2
name: auth-svc
description: Java Spring Boot auth/RBAC (gRPC :8120) — chart độc lập, cài riêng.
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../common"
